### ISSUE TITLE
How to autostart & minimize

### ISSUE THREAD

**Issue by wmd0701** [aarron-lee/simple-ryzen-tdp#2]
Many many thanks for this excellent app which makes easy TDP tuning possible on Linux! As a Linux noob I have just one question: how I can autostart it and hide / minimize it on system boot? Currently I add it to system autostart list (Garuda Linux, KDE), it indeed starts with Kate, but I sadly havent found a way to auto-minimize the window. I tried some parameters like --minimized, --hide... but none of them work. Deeply appreciated for any tips!

**Comment by aarron-lee** [comment]
There's a tray menu with a `Toggle Window` button, the window visibility status is persisted across reboots.

![image](https://github.com/aarron-lee/simple-ryzen-tdp/assets/9145965/c8dba988-655a-427d-b004-c61a1f0a9f93)

alternatively, you can go into the `~/.config/ryzen-tdp-settings.json`, and modify it by setting "isWindowHidden" to true.

example json:

```json
{
  "ryzenadjPath": "/usr/local/bin/ryzenadj",
  "appVersion": "1.0.4",
  "defaultTdp": 7,
  "tdpRange": [
    5,
    28
  ],
  "preserveTdpOnSuspend": true,
  "isWindowHidden": true
}
```
